CREATE DATABASE CASERNES;
\c CASERNES;

CREATE TABLE APPARTIENT_A (
  id VARCHAR(42),
  id_1 VARCHAR(42),
  PRIMARY KEY (id, id_1)
);

CREATE TABLE CAMION (
  id VARCHAR(42),
  latitude VARCHAR(42),
  longitude VARCHAR(42),
  id_1 VARCHAR(42),
  PRIMARY KEY (id)
);

CREATE TABLE CASERNE (
  id VARCHAR(42),
  rue VARCHAR(42),
  ville VARCHAR(42),
  PRIMARY KEY (id)
);

CREATE TABLE COMPOSE (
  id VARCHAR(42),
  id_1 VARCHAR(42),
  PRIMARY KEY (id, id_1)
);

CREATE TABLE EQUIPE (
  id VARCHAR(42),
  id_1 VARCHAR(42),
  status VARCHAR(42),
  id_2 VARCHAR(42),
  PRIMARY KEY (id)
);

CREATE TABLE INCENDIE (
  id VARCHAR(42),
  latitude VARCHAR(42),
  longitude VARCHAR(42),
  PRIMARY KEY (id)
);

CREATE TABLE POMPIER (
  id VARCHAR(42),
  nom VARCHAR(42),
  prenom VARCHAR(42),
  id_1 VARCHAR(42),
  PRIMARY KEY (id)
);

ALTER TABLE APPARTIENT_A ADD FOREIGN KEY (id_1) REFERENCES EQUIPE (id);
ALTER TABLE APPARTIENT_A ADD FOREIGN KEY (id) REFERENCES POMPIER (id);
ALTER TABLE CAMION ADD FOREIGN KEY (id_1) REFERENCES CASERNE (id);
ALTER TABLE COMPOSE ADD FOREIGN KEY (id_1) REFERENCES EQUIPE (id);
ALTER TABLE COMPOSE ADD FOREIGN KEY (id) REFERENCES CAMION (id);
ALTER TABLE EQUIPE ADD FOREIGN KEY (id_2) REFERENCES INCENDIE (id);
ALTER TABLE EQUIPE ADD FOREIGN KEY (id_1) REFERENCES CASERNE (id);
ALTER TABLE POMPIER ADD FOREIGN KEY (id_1) REFERENCES CASERNE (id);