-- Database: emergency

-- DROP DATABASE IF EXISTS emergency;

DROP TABLE IF EXISTS FIREMAN_INTERVENTION;
DROP TABLE IF EXISTS TRUCK_INTERVENTION;
DROP TABLE IF EXISTS TRUCK;
DROP TABLE IF EXISTS INTERVENTION;
DROP TABLE IF EXISTS FIREMAN;
DROP TABLE IF EXISTS ALERT;
DROP TABLE IF EXISTS FIRE;
DROP TABLE IF EXISTS STATION;


CREATE TABLE ALERT (
  id SERIAL,
  date TIMESTAMP,
  longitude REAL,
  latitude REAL,
  intensity INTEGER,
  id_fire INTEGER,
  PRIMARY KEY (id)
);

CREATE TABLE FIRE (
  id SERIAL,
  longitude REAL,
  latitude REAL,
  intensity INTEGER,
  status VARCHAR(50),
  PRIMARY KEY (id)
);

CREATE TABLE FIREMAN (
  id SERIAL,
  firstname VARCHAR(50),
  lastname VARCHAR(50),
  power  INTEGER,
  id_station INTEGER,
  PRIMARY KEY (id)
);

CREATE TABLE INTERVENTION (
  id SERIAL,
  date TIMESTAMP,
  status VARCHAR(50),
  id_fire INTEGER,
  PRIMARY KEY (id)
);

CREATE TABLE TRUCK_INTERVENTION (
  id_truck INTEGER,
  id_intervention INTEGER,
  PRIMARY KEY (id_truck, id_intervention)
);

CREATE TABLE STATION (
  id SERIAL,
  longitude REAL,
  latitude REAL,
  PRIMARY KEY (id)
);

CREATE TABLE TRUCK (
  id SERIAL,
  longitude VARCHAR(50),
  latitude VARCHAR(50),
  power  INTEGER,
  id_station INTEGER,
  PRIMARY KEY (id)
);

CREATE TABLE FIREMAN_INTERVENTION (
  id_fireman INTEGER,
  id_intervention INTEGER,
  PRIMARY KEY (id_fireman, id_intervention)
);

ALTER TABLE ALERT ADD FOREIGN KEY (id_fire) REFERENCES FIRE (id);
ALTER TABLE INTERVENTION ADD FOREIGN KEY (id_fire) REFERENCES FIRE (id);
ALTER TABLE FIREMAN ADD FOREIGN KEY (id_station) REFERENCES STATION (id);
ALTER TABLE TRUCK_INTERVENTION ADD FOREIGN KEY (id_truck) REFERENCES TRUCK (id);
ALTER TABLE TRUCK_INTERVENTION ADD FOREIGN KEY (id_intervention) REFERENCES INTERVENTION (id);
ALTER TABLE TRUCK ADD FOREIGN KEY (id_station) REFERENCES STATION (id);
ALTER TABLE FIREMAN_INTERVENTION ADD FOREIGN KEY (id_fireman) REFERENCES FIREMAN (id);
ALTER TABLE FIREMAN_INTERVENTION ADD FOREIGN KEY (id_intervention) REFERENCES INTERVENTION (id);
